# Generated by Django 3.0.8 on 2020-07-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='membership',
        ),
    ]
