# Generated by Django 3.0.8 on 2020-09-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersignups',
            options={'verbose_name_plural': 'NewsLetterSignups'},
        ),
    ]
