# Generated by Django 3.0.8 on 2020-07-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership',
            new_name='membership_type',
        ),
    ]
