# Generated by Django 3.0.8 on 2020-07-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20200717_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user_memdership',
            new_name='user_membership',
        ),
    ]
