# Generated by Django 3.0.8 on 2020-07-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200713_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orignal_cart',
        ),
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(default=''),
        ),
    ]
