# Generated by Django 3.0.8 on 2020-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_stripe_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_receipt',
            field=models.URLField(default='1', max_length=254),
        ),
    ]
