# Generated by Django 3.0.8 on 2020-07-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200730_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
