# Generated by Django 3.0.8 on 2020-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200902_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
