# Generated by Django 3.0.8 on 2020-08-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='product',
            new_name='name_product',
        ),
    ]
