# Generated by Django 3.0.8 on 2020-08-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='on_sale',
            new_name='display_items',
        ),
    ]
