# Generated by Django 3.0.8 on 2020-08-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcomment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
