# Generated by Django 3.0.8 on 2020-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200918_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='was_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
